version: 2.1

orbs:
  node: circleci/node@3.0.0
  codecov: codecov/codecov@1.2.0

jobs:
  setup:
    executor:
      name: node/default
    steps:
      - checkout
      - run:
          name: Install Node.js and NPM
          command: |
            curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
            sudo apt-get install -y nodejs
      - run: node --version
      - run: npm --version
      - node/install-packages:
          pkg-manager: npm
      - run: npm run lint
      - run: npm run cover
      - codecov/upload:
        file: coverage/*.json
      - run: npm run chromatic --project-token=${CHROMATIC_TOKEN}

  versioning:
    executor:
      name: node/default
    steps:
      - checkout
      - run:
          name: Check package version
          command: node scripts/check-version ericksouza02 meu-repo     

workflows:
  version: 2
  build-and-test:
    jobs:
      - setup
      - versioning:
          filters:
            branches: 
              ignore: main
            tags:
              ignore: /.*/