version: 2.1

orbs:
  node: circleci/node@3.0.0

jobs:
  setup:
    executor:
      name: node/default
    steps:
      - checkout
      - run:
          name: Install Node.js and NPM
          command: |
            curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
            sudo apt-get install -y nodejs
      - run: 
          name: Show Node and NPM Version
          command: |
            node --version
            npm --version
      - node/install-packages:
          pkg-manager: npm
      - run: 
          name: Run Lint Check
          command: npm run lint
      
      

  versioning:
    executor:
      name: node/default
    steps:
      - checkout
      - run:
          name: Check package version
          command: node scripts/check-version ericksouza02 meu-repo     

workflows:
  version: 2
  build-and-test:
    jobs:
      - setup
      - versioning:
          filters:
            branches: 
              ignore: main
            tags:
              ignore: /.*/