version: 2.1

orbs: 
  node: circleci/node@20.10.0

jobs: 
  setup:
    docker: 
      - image: circleci/node:20.10.0
    steps: 
      - checkout
      - node/install: 
        install-npm: true
      - run: node --version
      - run: npm --version

workflows:
  jobs: 
    - setup
