version: 2.1

orbs: 
  node: circleci/node@5.1.0

jobs: 
  setup:
    docker: 
      - image: circleci/node:16.15.0-browsers   
    steps: 
      - checkout
      - node/install: 
        install-npm: true
      - run: node --version
      - run: npm --version

workflow:
  ci: 
    - setup
