version: 2.1

orbs: 
  node: circleci/node@4.0.2

jobs: 
  setup:
    docker: 
    
      - image: circleci/node:4.0.2
    steps: 
      - node/install: 
        install-npm: true
      - run: node --version
      - run: npm --version

workflow:
  jobs: 
    - setup
